steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/aif-pbk:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/aif-pbk:$SHORT_SHA']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment/deployment.yaml
  - --image=asia.gcr.io/$PROJECT_ID/aif-pbk:$SHORT_SHA
  - --location=asia-southeast2
  - --cluster=aif-pbk