apiVersion: v1
kind: Service
metadata:
  name: pbk-svc
  namespace: default
  labels:
    app: pbk
    service: pbk-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: tcp
  selector:
    app: pbk
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pbk
  labels:
    account: pbk
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pbk
  namespace: default
  labels:
    app: pbk
spec:
  serviceName: pbk-svc
  replicas: 1
  selector:
    matchLabels:
      app: pbk
  template:
    metadata:
      labels:
        app: pbk
    spec:
      serviceAccountName: pbk
      containers:
      - name: pbk
        image: asia.gcr.io/aif-pbk/aif-pbk
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "2048Mi"
          limits:
            cpu: "2"
            memory: "4Gi"
        env:
          - name: PORT_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_PORT
          - name: HOST_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_HOST
          - name: USER_LOCAL
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: PG_USER
          - name: PASSWORD_LOCAL
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: PG_PASSWORD
          - name: DATABASE_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_DB_NAME
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: API_KEY
  volumeClaimTemplates:
  - metadata:
      name: scoreezy-redis-pvc
      annotations:
        volume.beta.kubernetes.io/storage-class: "premium-rwo"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: pbk-hpa
  namespace: default
  labels:
    app: pbk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pbk
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: Utilization
        averageUtilization: 75
        