apiVersion: v1
kind: ServiceAccount
metadata:
  name: pbk-ksa
  namespace: pbk
---
apiVersion: v1
kind: Service
metadata:
  name: pbk-svc
  namespace: pbk
  labels:
    app: pbk
    service: pbk-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: tcp
  selector:
    app: pbk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbk
  namespace: pbk
  labels:
    app: pbk
spec:
  selector:
    matchLabels:
      app: pbk
  template:
    metadata:
      labels:
        app: pbk
    spec:
      serviceAccountName: pbk-ksa
      containers:
      - name: pbk
        image: asia.gcr.io/aif-staging/aif-pbk
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "1024Mi"
          limits:
            cpu: "1"
            memory: "2Gi"
        env:
          - name: PORT_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_PORT
          - name: HOST_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_HOST
          - name: USER_LOCAL
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: PG_USER
          - name: PASSWORD_LOCAL
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: PG_PASSWORD
          - name: DATABASE_LOCAL
            valueFrom:
              configMapKeyRef:
                name: pbk-config
                key: PG_DB_NAME
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: pbk-secret
                key: API_KEY